version: 2.1
jobs:

  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Jar File
          command: mvn install
      - run:
          name: Build Docker Image
          command: |
            docker build -t davidnjau21/circleci .

workflows:
  buildJarFile:
    jobs:
      - build
