orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: davidnjau21/circleci
      DOCKERHUB_PASSWORD: Sc281-6736/2014
    docker:
      - image: circleci/node:latest
        auth:
          username: davidnjau21
          password: Sc281-6736/2014

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: davidnjau21
          password: Sc281-6736/2014

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Jar File
          command: mvn install
      - run:
          name: Build Docker and push Image
          command: |
            docker build -t davidnjau21/circleci .
            echo "Sc281-6736/2014" | docker login -u "davidnjau21" --password-stdin
            docker push davidnjau21/circleci:latest
            docker logout

  deploy:
    docker:
      - image: cimg/node:14.18.2
    steps:
      - run: sudo apt install rsync
      - run:
          name: SSH into remote server
          command: |
            rsync -avz -e "ssh" --progress build david@199.192.27.107:build


workflows:
  version: 2
  buildJarFile:
    jobs:
      - deploy

