orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: davidnjau21/circleci
      DOCKERHUB_PASSWORD: Sc281-6736/2014
    docker:
      - image: circleci/node:latest
        auth:
          username: davidnjau21
          password: Sc281-6736/2014

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: davidnjau21
          password: Sc281-6736/2014

    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Jar File
          command: mvn install
          store_artifacts:
            - /tmp/artifacts

  deploy:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: davidnjau21
          password: Sc281-6736/2014
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t davidnjau21/circleci .
            echo "Sc281-6736/2014" | docker login -u "davidnjau21" --password-stdin
            docker push davidnjau21/circleci:latest
            docker logout

workflows:
  version: 2
  buildJarFile:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
