orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: davidnjau21/circleci
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: davidnjau21
          password: Sc281-6736/2014

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Build Jar File
          command: mvn install > jars
      - persist_to_workspace:
          root: jars
          paths:
            - .

  deploy:
    working_directory: ~/CircleCI
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /jarfiles
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t davidnjau21/circleci .
            echo "Sc281-6736/2014" | docker login -u "davidnjau21" --password-stdin
            docker push davidnjau21/circleci:latest
            docker logout

workflows:
  buildJarFile:
    jobs:
      - build
      - deploy
